# Generated by Django 6.1.1 on 2026-09-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
